apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qyxe
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0008-tenant/tkrw-pr712-0075-0008-app/devfile-sample-qyxe@sha256:c5fdde34e91febdc77b89573a36ddf3698af489b9bfd6942af0e29d0b4c54f1b
        name: my-nodejs
        resources: {}
status: {}
